apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-lcu0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tenant/appstudio/devfile-sample-python-basic-lcu0@sha256:e19bc424110d7b336492ff7136d82e3b586366e8a071724b8854b6160d2356a8
        name: my-python
        resources: {}
status: {}
