apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-5pwi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-5pwi
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-5pwi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-5pwi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-5pwi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tenant/appstudio/dc-metro-map-5pwi@sha256:0ae5bc079941532ad091ad399cd3413604cab61b00b8dbc2c4ee68bf1af09fa9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
